#!/usr/bin/env node
// Derives a theme's four FLAT mascot variants from its own rig.
//
//   node scripts/flatten-rig.mjs [<slug> ...]      (default: every theme that ships a rig)
//
// Why derive rather than draw: desktop renders the rig, Android and remote browsers render
// the flat art. Two hand-maintained sets of the same character drift, and when they do,
// half the users see last season's face. The rig is the source; this is a projection of it.
//
// It keeps hats, tails, whiskers and every other decoration, because it keeps the whole rig
// and only decides which face group survives.
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
// The app's MascotVariant union -> the rig face each one shows. `inquisitive` predates the
// rig contract's `curious`; same expression. There is deliberately no `dizzy`: the app
// cannot display one, so writing the file only creates a dead asset.
export const FLAT = { idle: 'idle', welcome: 'welcome', inquisitive: 'curious', shocked: 'shocked' };
const FACES = ['idle', 'welcome', 'curious', 'shocked', 'dizzy', 'blink', 'happy', 'shutdown'];

/** Everything between a group's opening tag and its matching close, plus the span it covers. */
function groupSpan(svg, id) {
  const open = svg.search(new RegExp(`<g\\b[^>]*\\bid="${id}"`));
  if (open < 0) return null;
  const afterTag = svg.indexOf('>', open);
  if (svg[afterTag - 1] === '/') return { start: open, end: afterTag + 1 };  // self-closing
  let i = afterTag + 1, depth = 1;
  while (i < svg.length && depth > 0) {
    const no = svg.indexOf('<g', i), nc = svg.indexOf('</g>', i);
    if (nc < 0) break;
    if (no >= 0 && no < nc) { depth++; i = no + 2; }
    else { depth--; if (depth === 0) return { start: open, end: nc + 4 }; i = nc + 4; }
  }
  return null;
}

export function flatten(rig, variant) {
  const keep = FLAT[variant];
  if (!keep) throw new Error(`no flat variant "${variant}" — the app displays only ${Object.keys(FLAT).join(', ')}`);
  let svg = rig;
  // Drop every face but the one this variant shows, back to front so earlier offsets hold.
  const spans = FACES.filter((f) => f !== keep)
    .map((f) => groupSpan(svg, `rig-face-${f}`)).filter(Boolean)
    .sort((a, b) => b.start - a.start);
  for (const s of spans) svg = svg.slice(0, s.start) + svg.slice(s.end);
  // The survivor paints: it is the only face left, so its display:none must go.
  svg = svg.replace(new RegExp(`(<g id="rig-face-${keep}")[^>]*>`), '$1>');
  // The peek mittens are cloned by the app's edge overlay, never drawn in place.
  for (const id of ['rig-hand-peek-left', 'rig-hand-peek-right']) {
    const s = groupSpan(svg, id);
    if (s) svg = svg.slice(0, s.start) + svg.slice(s.end);
  }
  return svg.replace(/<!--[\s\S]*?-->/,
    `<!-- Generated by scripts/flatten-rig.mjs from mascot-rig.svg — do not edit by hand.\n` +
    `       Flat "${variant}" variant (rig face "${keep}"). Android and remote browsers render\n` +
    `       this; desktop renders the rig. Regenerate whenever the rig changes. -->`);
}

function main(slugs) {
  const dir = join(ROOT, 'themes');
  const targets = slugs.length ? slugs : readdirSync(dir).filter((s) =>
    existsSync(join(dir, s, 'assets', 'mascot-rig.svg')));
  let n = 0;
  for (const slug of targets) {
    const rigPath = join(dir, slug, 'assets', 'mascot-rig.svg');
    if (!existsSync(rigPath)) { console.error(`${slug}: no mascot-rig.svg`); continue; }
    const rig = readFileSync(rigPath, 'utf8');
    for (const v of Object.keys(FLAT)) {
      writeFileSync(join(dir, slug, 'assets', `mascot-${v}.svg`), flatten(rig, v));
      n++;
    }
    console.log(`${slug}: ${Object.keys(FLAT).length} flat variants`);
  }
  console.log(`${n} file(s) written from ${targets.length} rig(s)`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) process.exit(main(process.argv.slice(2)));
